[package]
name = "rust-geometry-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
rust_decimal = { version = "1.17.0", features = ["serde", "maths"] }
rust_decimal_macros = "1.17.0"
sha2 = "0.10.2"
hex = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"